### ISSUE TITLE
Completion of makecode_radio.py

### ISSUE THREAD

**Issue by rhubarbdog** [ukBaz/ukBaz.github.io#29]
Hi
you responded to <a href="https://github.com/bbcmicrobit/micropython/issues/617">bbcmicrobit/micropython issue #617</a> and gave me a link to your work on <a href="https://ukbaz.github.io/howto/ubit_radio.html">makecode radio</a>
I needed to receive packets so i have completed the class here's an out line of my mods
```
1) Added broadcast rate and channel and others to radio.config              
2) added endian to .to_bytes() method                                       
3) changed some variable names                                              
4) Added receive_packet method                                              
5) Added support for packet type 4 float                                    
6) Limit message length to 19                                               
7) Limit send_value: name length to 8                                       
8) Added support for packet type 5 value with float                         
```
You say in the document you think this should be part of the micropython repository.  I agree the main issue is the license are you willing to re-license `howto/ubit_radio.html` to an MIT license.
currently my code contains a link to the creative commons license, but i'll change it if you do

**Comment by ukBaz** [comment]
Hi @rhubarbdog,

Thank you for getting in contact with me on this. I am happy for you to use the code from the article under am MIT license. I would like to leave the article as Creative Commons. 

Does that work for you?

Regards,
Barry

**Comment by rhubarbdog** [comment]
Hi
I've now published my code feel free to reference it in your document. Here's a link https://github.com/rhubarbdog/microbit-radio

**Comment by ukBaz** [comment]
Nicely done. Thanks for sharing.

**Comment by ukBaz** [comment]
Thanks @rhubarbdog. I've put a link in the blog to your repo.
https://ukbaz.github.io/howto/ubit_radio.html
